version: "3.9"
services:
  service-registry:
    image: bredex/service-registry
    ports:
      - 8761:8761
  account-service:
    image: bredex/account-service
    environment:
      - eureka.client.serviceUrl.defaultZone=http://service-registry:8761/eureka/
    ports:
      - 8081:8080
    depends_on:
      - service-registry
  inventory-service:
    image: bredex/inventory-service
    environment:
      - eureka.client.serviceUrl.defaultZone=http://service-registry:8761/eureka/
    ports:
      - 8082:8080
    depends_on:
      - service-registry
  lending-service:
    image: bredex/lending-service
    environment:
      - eureka.client.serviceUrl.defaultZone=http://service-registry:8761/eureka/
    ports:
      - 8083:8080
    depends_on:
      - service-registry
      - account-service
      - inventory-service
    